### PR TITLE
[SOL] Advance llvm commit

### PR DESCRIPTION
**Pull request by LucasSte**
There are multiple reports of stack problems in the current platform tools version. I think making an intermediate release that addresses some of the problems (e.g. increasing reliability of error messages and not allowing function calls to overwrite values in the stack) would be good at this point.

### CODE REVIEW

**Comment by LucasSte** [comment]
There some tweaks in this PR to fix the failing CI, because we couldn't download anymore the pre-built Docker image and the pre-built LLVM binaries from the upstream Rust repository.

Also, the compiler-builtins crate has had an update, rendering it incompatible with 1.75.0.

As we'll soon upgrade to Rust 1.79, I won't pick up this commit.

**Review by dmakarov — APPROVED** [review]
I think there's an option in config.toml that can be set to not download llvm binaries by the bootstrap. Anyway, approving.

**Comment by LucasSte** [comment]
> I think there's an option in config.toml that can be set to not download llvm binaries by the bootstrap. Anyway, approving.

This one?

https://github.com/anza-xyz/rust/blob/696ef741a6b654a4fe9f46bc47b502049e919aa9/config.toml#L111

It is already set to false.

**Comment by dmakarov** [comment]
> > I think there's an option in config.toml that can be set to not download llvm binaries by the bootstrap. Anyway, approving.
> 
> This one?
> 
> https://github.com/anza-xyz/rust/blob/696ef741a6b654a4fe9f46bc47b502049e919aa9/config.toml#L111
> 
> It is already set to false.

Yes, curious why it doesn’t have any effect. Maybe for CI a completely separate config.toml is created somehow in the CI environment?

**Comment by dmakarov** [comment]
it’s ok to merge this as is.

**Pull request merged**
